import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { JwtTokenProvider } from "./Provider/JWTTokenProvider";
import ThirdProvider from "./Provider/WalletContextProvider";
require("@solana/wallet-adapter-react-ui/styles.css");
import Header from "./components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <JwtTokenProvider>
          <ThirdProvider>
            <Header />
            {children}
          </ThirdProvider>
        </JwtTokenProvider>
      </body>
    </html>
  )
}
